name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        env:
          DOCKER_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKER_REPO: ${{ vars.DOCKERHUB_REPO }}
        run: |
          # Build the image
          docker build -t $DOCKER_REPO:latest .
          
          # Login to DockerHub
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          
          # Push the image
          docker push $DOCKER_REPO:latest

  validate:
    needs: build  # This ensures validate runs after build
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run Docker image
        env:
          DOCKER_REPO: ${{ vars.DOCKERHUB_REPO }}
        run: |
          # Pull the image we just built
          docker pull $DOCKER_REPO:latest
          
          # Run the container in detached mode, mapping port 80
          docker run -d -p 80:80 --name web $DOCKER_REPO:latest
          
          # Wait a few seconds for Nginx to start
          sleep 5
          
          # Test if index.html is accessible
          if curl -f http://localhost/index.html; then
            echo "Successfully validated index.html is accessible"
          else
            echo "Failed to access index.html"
            exit 1
          fi
