name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          # Build and tag with a local name
          docker build -t nginx-test:latest .
          
          # Save the image to a tar file to share between jobs
          docker save nginx-test:latest > nginx-test.tar
          
      - name: Upload image artifact
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: docker-image
          path: nginx-test.tar

  validate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4  # Updated from v3 to v4
        with:
          name: docker-image
          
      - name: Load Docker image
        run: |
          # Load the image from tar
          docker load < nginx-test.tar
          
          # Run the container
          docker run -d -p 80:80 --name web nginx-test:latest
          
          # Wait for Nginx to start
          sleep 5
          
          # Test if index.html is accessible
          if curl -f http://localhost/index.html; then
            echo "Successfully validated index.html is accessible"
          else
            echo "Failed to access index.html"
            docker logs web
            exit 1
          fi
